---
title: "Carbonate chemistry, Point B (SAMI data)"
author: "Jean-Pierre Gattuso and Samir Alliouane"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  rmarkdown::html_document:
    theme: paper
    number_sections: false
---

```{r set-up, echo=FALSE, warning=FALSE, message=FALSE, include =FALSE}
Sys.setlocale("LC_ALL", "en_US.UTF-8")
library(ggplot2)
library(seacarb) 
library(reshape2)
library(plyr)
library(zoo)
library(tidyr)
library("lmodel2") # model II regression
library("dplyr", warn.conflicts = FALSE)
library(lubridate)
library(knitr)
#opts_knit$set(root.dir = '../')
library(scales)
library(dygraphs)
library(xts)
library(stringr)
```

```{r define_functions, echo=FALSE}
rm(list = ls())
## theme to format the plots
Sys.setenv(TZ='UTC') # on utilise UTC

#################### Regression function 
####
# function regression plot with model II equation (MA) in title
## Dans labs ajout de la variable TITRE pour mettre titre avant chaque graphe
ggreg2 <- function (fit, xdata, ydata) { # x and y are the names of the variables
  fit_data <- data.frame(fit$x, fit$y)
  colnames(fit_data) = c(xdata, ydata)
reg <- fit$regression.results[2,] #one selects MA only
intercept <- reg$Intercept
slope <- reg$Slope
  ggplot(data = fit_data, aes_string(x = xdata, y = ydata)) + 
  geom_point(size = 3, col = "blue") +
  geom_abline(aes(intercept = fit$regression.results[2,2], slope = fit$regression.results[2,3]),
              colour = "blue")  + 
  labs(title = paste(titre,"\n Adj R2 = ", signif(fit$rsquare, 3),
                     "; Intercept =", signif(intercept, 3),
                     "; Slope =", signif(slope, 3),
                     "; P =", signif(fit$P.param, 3)))
}

mytheme <- theme_bw() +
  theme(axis.text.x=element_text(size=16, color="black"),
        axis.title.x=element_text(face="bold", size=16),
        axis.text.y=element_text(size=16, color="black"),
        axis.title.y=element_text(face="bold", size=16),
        plot.title = element_text(face="bold", size=14)
)

```


```{r make data file, echo=FALSE, warning=FALSE, message=FALSE}
# data prepare --> Look at "2015-06-02_seafet_pointB.R" in "pb_R" folder
#---------- Lecture des fichiers "Raw_seaFET..." un par un via la boucle.
# Dataframe "TAB" is done.

file_list <- list.files(path  = "../../pCloud Sync/piSami-pH/sami_data/sami_processed/Salinity_corrected/PointB/", pattern = "Raw_SAMI.*.txt")

if (length(file_list) == 0) {stop()} # script does not run if there is no data file to read
ii <- 0
for (file in file_list){ 
  ii <- ii + 1
  tmp <- read.table(paste("../../pCloud Sync/piSami-pH/sami_data/sami_processed/Salinity_corrected/PointB/", file, sep = ""), header = F, dec = ".", as.is = T, sep = "\t", skip = 4, fill = TRUE)
  if (ii == 1) {z <- tmp} else {z <- rbind(z, tmp)}
}

colnames(z)  <- c("datetime","ph_sami", "ph_error_sami", "temp_int_sami", "temp_ext_sami","flag_sami")

# add deployment period = Fisrt, Add manualy the deployement number in the title file and take last digit in the title file
z$deployment <- as.numeric(substr(str_extract(file, "-[0-9][0-9]"),2,3))

# # put the file in the processed file
# if (length(file_list) > 0) {
#   for (file in file_list){ 
#     # move new zip files from PointB to processed PointB 
#     system(paste0("mv ../../pCloud Sync/piSami-pH/sami_data/sami_processed/Salinity_corrected/PointB/", file, " ../../pCloud Sync/piSami-pH/sami_data/sami_processed/Salinity_corrected/PointB/PointB_processed"))
#   }
# }

# Convert datetime
z$datetime <- mdy_hms(z$datetime)

TAB <- z 

# supprimer les données erronées 
TAB <- TAB %>% 
  dplyr::filter(flag_sami == 0)
save(TAB, file = "../../pCloud Sync/piSami-pH/sami_data/sami_processed/Salinity_corrected/PointB/SAMI_ptb.csv") 

```
