---
title: "Sète carbonate Chemistry"
author: "samir"

date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  rmarkdown::html_document:
    theme: paper
    number_sections: false
---

```{r set-up, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
rm(list = ls())
library(tidyverse)
library(robfilter)
library(seacarb)
library(gridExtra)
library(reshape2)
library(lubridate)
library(lmtest)
library(grid)
library(viridis)
library(dygraphs)
require("knitr")
library("lmodel2")
library(dygraphs)
library(xts)
library(seismicRoll)
library(scales)
knitr::opts_chunk$set(echo = TRUE)
```

```{r lydia data, echo=FALSE, warning=FALSE, message=FALSE}
#open files
ctd <- read.table("./SETE_20161011_20170925_compiled.csv", header=T, sep=",", dec=".", as.is=T)
sf <- read.table("./SF_SETE.csv", header=T, sep=",", dec=".", as.is=T)
# convert the datetime into date time format
ctd$time_GMT<- ymd_hms(ctd$time_GMT, tz="UTC")
sf$time_GMT<- ymd_hms(sf$time_GMT, tz="UTC")
# round the datetime to minute. help in this link 
#https://statistique-et-logiciel-r.com/gerer-les-dates-et-les-heures-avec-le-package-lubridate/
ctd$time_GMT<- floor_date(ctd$time_GMT, unit="minute")
sf$time_GMT<- floor_date(sf$time_GMT, unit="minute")

#merge the 2 df in one with CTD data and SF data on the same line for the same timestamp
# The important argument here is "all=TRUE" to get all values.
all <- merge(ctd,sf, by="time_GMT", all=TRUE)


```
Dear Lydia,

Here and example of Rmarkdown with nice disign and tabs to change chapter.
To do tabs look at the code just the line below (I choose to not show the code on the html so you will not see it here).

good sites:

- https://dr-harper.github.io/rmarkdown-cookbook/changing-font-colour.htmlG
- https://holtzy.github.io/Pimp-my-rmd/
  
#{.tabset .tabset-fade .tabset-pills}

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }
h3{ /* Header 3 */
  font-size: 22px;
  <!-- font-family: "Times New Roman", Times, serif; -->
}
</style>

##**Normal plot**

### First plot
```{r normal plot, echo=FALSE, warning=FALSE, message=FALSE}
# normal plot
colors <- c("red", "blue")
plot_t_n <- ggplot( ) +
            geom_point(data=all, aes(x=time_GMT, y= ctd_temp_C, colour="CTD"),size=0.7 ) +
            geom_point(data=all, aes(x=time_GMT, y=SF_T_degrC, color= "seaFET"),size=0.4)+
            labs(x = "Time", y ="Temperature", title = "") +
            scale_colour_manual( values=colors)+

            theme_bw() +
            scale_x_datetime(minor_breaks  = "1 week ")+
            theme(legend.position="top",
                     legend.text=element_text(size=14, colour="black"),
                     axis.text=element_text(size=15),
                     axis.title.x= element_text(size =14),
                     legend.title=element_blank()
                     )

print(plot_t_n)
```

##**Dygraph plot**
### Second plot
```{r dygraph plot, echo=FALSE, warning=FALSE, message=FALSE}

# dygraph plot (interactive plot)
#select your variable to plot
temp_xts <- dplyr::select(all, time_GMT,ctd_temp_C, SF_T_degrC)
#put it in xts special format to use dygraph
temp_xts <- as.xts(temp_xts, order.by=temp_xts$time_GMT)
# plot it
dygraph(temp_xts, ylab = "Temperature (°C)") %>%
  dySeries("ctd_temp_C", drawPoints = TRUE, pointSize=1, col="red", label = "CTD")%>%
  dySeries("SF_T_degrC", drawPoints = TRUE, pointSize=0.7,col = "blue", label = "seaFET") %>%
  #dyLimit(0.02,color =  "red")%>%
  dyLegend(show = "always", width = 600)%>%
 # dyAxis("y",valueRange = c(-0.1, 0.11))%>%
  dyRangeSelector(height = 30)
```